### ISSUE TITLE
Acronym at end of a sentence parses incorrectly

### ISSUE THREAD

**Issue by kprussing** [kprussing/pandoc-acro#1]
The following fails to translate the acronym because the punctuation.

    ---
    acronyms:
      AFAIK:
        short: AFAIK
        long: as far as I know
    ...

    +AFAIK.

Outputs:

    $ pandoc -F pandocacro/__init__.py mwe.md
    +AFAIK.

**Comment by braydenD6** [comment]
Hi, I cloned this repo and implemented a fix. I tried pushing my branch to the repo and got permission denied, perhaps I should have asked for permissions before I got started. My bad, this is my first attempt at contributing to an open source project, so still learning the ins and outs of this. Would you be able to give me the permissions to push to the repo so I can create a PR? Thanks.

**Comment by kprussing** [comment]
Thanks for taking the initiative! I only noticed this bug yesterday and hadn't had a chance to actually look into it.

The basic workflow follows the usual [fork and pull request method](https://guides.github.com/activities/forking/). Feel free to open a pull request and I'll take a look.

**Comment by kprussing** [comment]
closed by https://github.com/kprussing/pandoc-acro/commit/c2005a8ac1ce53a3bbe9ea5e5c09cbb88ad5ff38
