### ISSUE TITLE
Quote blocks prevent acronym expansion for simple usage

### ISSUE THREAD

**Issue by kprussing** [kprussing/pandoc-acro#2]
Similar to #1, the parsing of simple `+key` quotes fails inside quote blocks.  Consider:

```
---
acronyms:
  mfe:
    short: mfe
    long: minimum failing example
...

-   '+mfe'
-   "+mfe"
-   '[+mfe]{}'
-   "[+mfe]{.long}"
```

One would expect all acronyms to expand, but what one gets instead is

```
-   '+mfe'
-   "+mfe"
-   'minimum failing example (mfe)'
-   "minimum failing example"
```

Note how spans do the right thing but bare quote blocks do not.

**Comment by GuND0Wn151** [comment]
what kind of output your excpecting here
like mfe - minimum failing example?

**Comment by kprussing** [comment]
Similar to what I said in the second code block but based on the README. But it's a little more subtle because of how the translation the LaTeX should work.  I just pushed a test that checks for the expected output.
